# Generated by Django 6.0 on 2025-12-12 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], default='user', max_length=10),
        ),
        migrations.CreateModel(
            name='Peminjaman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.IntegerField()),
                ('status', models.CharField(choices=[('dipinjam', 'Dipinjam'), ('dikembalikan', 'Dikembalikan')], default='dipinjam', max_length=15)),
                ('catatan', models.TextField(blank=True, null=True)),
                ('tanggal_pinjam', models.DateTimeField(auto_now_add=True)),
                ('tanggal_kembali', models.DateTimeField(blank=True, null=True)),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.barang')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.users')),
            ],
        ),
    ]
