# Generated by Django 5.2.8 on 2025-12-26 15:52

import api.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_users_departemen_users_foto_users_phone_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="feedback",
            options={"ordering": ["-tanggal"]},
        ),
        migrations.AlterModelOptions(
            name="peminjaman",
            options={"ordering": ["-tanggal_pinjam"]},
        ),
        migrations.AlterModelOptions(
            name="riwayattransaksi",
            options={"ordering": ["-tanggal"]},
        ),
        migrations.AlterField(
            model_name="barang",
            name="harga",
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="barang",
            name="minimum",
            field=models.IntegerField(
                default=5, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="barang",
            name="nama",
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="barang",
            name="stok",
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="pesan",
            field=models.TextField(validators=[api.models.validate_pesan_not_empty]),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedbacks",
                to="api.users",
            ),
        ),
        migrations.AlterField(
            model_name="peminjaman",
            name="barang",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="peminjaman",
                to="api.barang",
            ),
        ),
        migrations.AlterField(
            model_name="peminjaman",
            name="jumlah",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="peminjaman",
            name="status",
            field=models.CharField(
                choices=[("dipinjam", "Dipinjam"), ("dikembalikan", "Dikembalikan")],
                db_index=True,
                default="dipinjam",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="peminjaman",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="peminjaman",
                to="api.users",
            ),
        ),
        migrations.AlterField(
            model_name="riwayattransaksi",
            name="barang",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transaksi",
                to="api.barang",
            ),
        ),
        migrations.AlterField(
            model_name="riwayattransaksi",
            name="jumlah",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="riwayattransaksi",
            name="tipe",
            field=models.CharField(
                choices=[("masuk", "Masuk"), ("keluar", "Keluar")],
                db_index=True,
                default="masuk",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="riwayattransaksi",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transaksi",
                to="api.users",
            ),
        ),
        migrations.AlterField(
            model_name="users",
            name="departemen",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="users",
            name="email",
            field=models.EmailField(
                blank=True, db_index=True, max_length=254, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="users",
            name="nama",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="users",
            name="password",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="users",
            name="role",
            field=models.CharField(
                choices=[("user", "User"), ("admin", "Admin")],
                db_index=True,
                default="user",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="users",
            name="username",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True, unique=True
            ),
        ),
        migrations.AddIndex(
            model_name="barang",
            index=models.Index(fields=["nama"], name="api_barang_nama_877611_idx"),
        ),
        migrations.AddIndex(
            model_name="barang",
            index=models.Index(fields=["stok"], name="api_barang_stok_8e8bef_idx"),
        ),
        migrations.AddIndex(
            model_name="barang",
            index=models.Index(fields=["harga"], name="api_barang_harga_8b6a5b_idx"),
        ),
        migrations.AddIndex(
            model_name="barang",
            index=models.Index(
                fields=["stok", "minimum"], name="api_barang_stok_1a011b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="feedback",
            index=models.Index(
                fields=["tanggal"], name="api_feedbac_tanggal_0cefd1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="feedback",
            index=models.Index(
                fields=["user", "tanggal"], name="api_feedbac_user_id_45c8c9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="peminjaman",
            index=models.Index(
                fields=["tanggal_pinjam"], name="api_peminja_tanggal_ba2d33_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="peminjaman",
            index=models.Index(
                fields=["status", "tanggal_pinjam"],
                name="api_peminja_status_08648b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="peminjaman",
            index=models.Index(
                fields=["barang", "status"], name="api_peminja_barang__f90f30_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="peminjaman",
            index=models.Index(
                fields=["user", "status"], name="api_peminja_user_id_cccf69_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="peminjaman",
            index=models.Index(
                fields=["user", "tanggal_pinjam"], name="api_peminja_user_id_63ec6f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="riwayattransaksi",
            index=models.Index(
                fields=["tanggal"], name="api_riwayat_tanggal_93aeec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="riwayattransaksi",
            index=models.Index(
                fields=["tipe", "tanggal"], name="api_riwayat_tipe_39175b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="riwayattransaksi",
            index=models.Index(
                fields=["barang", "tanggal"], name="api_riwayat_barang__2d5f9f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="riwayattransaksi",
            index=models.Index(
                fields=["user", "tanggal"], name="api_riwayat_user_id_41db0b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="users",
            index=models.Index(
                fields=["nama", "role"], name="api_users_nama_6518b2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="users",
            index=models.Index(
                fields=["email", "role"], name="api_users_email_3bf09f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="users",
            index=models.Index(
                fields=["departemen", "role"], name="api_users_departe_a3a86c_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="barang",
            constraint=models.CheckConstraint(
                condition=models.Q(("stok__gte", 0)), name="stok_non_negative"
            ),
        ),
        migrations.AddConstraint(
            model_name="barang",
            constraint=models.CheckConstraint(
                condition=models.Q(("harga__gte", 0)), name="harga_non_negative"
            ),
        ),
        migrations.AddConstraint(
            model_name="barang",
            constraint=models.CheckConstraint(
                condition=models.Q(("minimum__gte", 0)), name="minimum_non_negative"
            ),
        ),
        migrations.AddConstraint(
            model_name="peminjaman",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["dipinjam", "dikembalikan"])),
                name="valid_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="peminjaman",
            constraint=models.CheckConstraint(
                condition=models.Q(("jumlah__gt", 0)), name="peminjaman_jumlah_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="riwayattransaksi",
            constraint=models.CheckConstraint(
                condition=models.Q(("tipe__in", ["masuk", "keluar"])), name="valid_tipe"
            ),
        ),
        migrations.AddConstraint(
            model_name="riwayattransaksi",
            constraint=models.CheckConstraint(
                condition=models.Q(("jumlah__gt", 0)), name="jumlah_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="users",
            constraint=models.CheckConstraint(
                condition=models.Q(("role__in", ["user", "admin"])), name="valid_role"
            ),
        ),
    ]
