# Generated by Django 5.2.8 on 2026-01-03 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_feedback_options_alter_peminjaman_options_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="peminjaman",
            name="valid_status",
        ),
        migrations.AddField(
            model_name="peminjaman",
            name="admin_verifier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_loans",
                to="api.users",
            ),
        ),
        migrations.AddField(
            model_name="peminjaman",
            name="alasan_peminjaman",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="peminjaman",
            name="alasan_reject",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="peminjaman",
            name="tanggal_verifikasi",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="peminjaman",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Approval"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("dipinjam", "Dipinjam"),
                    ("dikembalikan", "Dikembalikan"),
                ],
                db_index=True,
                default="pending",
                max_length=15,
            ),
        ),
        migrations.AddIndex(
            model_name="peminjaman",
            index=models.Index(
                fields=["admin_verifier", "tanggal_verifikasi"],
                name="api_peminja_admin_v_965768_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="peminjaman",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        ["pending", "approved", "rejected", "dipinjam", "dikembalikan"],
                    )
                ),
                name="valid_status",
            ),
        ),
    ]
